app/main/__init__.py
from flask import Blueprint

bp = Blueprint("main", __name__, template_folder="templates", static_folder="static")

from . import views

app/main/views.py
from flask import render_template, request, jsonify
from . import bp

@bp.route("/")
@bp.route("/home")
def index():
    return render_template("index.html")

@bp.route("/form")
def form():
    return render_template("form.html")

@bp.route("/form_post", methods=["POST"])
def form_post():
    data = request.get_json()
    print(data)
    return 200

app/main/templates/base.html
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Calls</title>
</head>

<body>
    <header>
        <a href="{{ url_for('main.index')}}">Home</a>
        <a href="{{ url_for('main.form')}}">Form</a>
    </header>
    {% block content %}
    {% endblock %}
</body>

</html>

app/main/templates/form.html
{% extends "base.html" %}
{% block content %}
<form id="content-form" action="" method="post">
    <label for="content-title">Title</label>
    <input id="content-title" name="content-title" type="text">
    <label for="content-body"></label>
    <textarea name="content-body" id="content-body" cols="30" rows="10"></textarea>
    <input type="submit" value="Submit">
</form>
<script src="{url_for}"></script>
{% endblock %}

app/main/templates/index.html
{% extends "base.html" %}

{% block content %}
<h1>Main Page</h1>
<div id="display">

</div>
{% endblock %}